### ISSUE TITLE
Not working with Android 14

### ISSUE THREAD

**Issue by caleblawrence** [Rapsssito/react-native-background-actions#200] opened 2023-11-28 17:54 UTC
I can't get this package to work on Android 14. It's causing the app to crash with this error: 
```
2023-11-14 14:17:48.728 30138-30138/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.compassionclips, PID: 30138
    java.lang.RuntimeException: Unable to start service com.asterinet.react.bgactions.RNBackgroundActionsTask@eccf065 with Intent { cmp=com.compassionclips/com.asterinet.react.bgactions.RNBackgroundActionsTask (has extras) }: java.lang.IllegalArgumentException: com.compassionclips: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4839)
        at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2289)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:205)
        at android.os.Looper.loop(Looper.java:294)
        at android.app.ActivityThread.main(ActivityThread.java:8177)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
     Caused by: java.lang.IllegalArgumentException: com.compassionclips: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
        at android.os.Parcel.createException(Parcel.java:3041)
        at android.os.Parcel.readException(Parcel.java:3024)
        at android.os.Parcel.readException(Parcel.java:2966)
        at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:6568)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:549)
        at android.app.PendingIntent.getActivity(PendingIntent.java:530)
        at android.app.PendingIntent.getActivity(PendingIntent.java:494)
        at com.asterinet.react.bgactions.RNBackgroundActionsTask.buildNotification(RNBackgroundActionsTask.java:45)
        at com.asterinet.react.bgactions.RNBackgroundActionsTask.onStartCommand(RNBackgroundActionsTask.java:89)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4821)
        at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2289) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:205) 
        at android.os.Looper.loop(Looper.java:294) 
        at android.app.ActivityThread.main(ActivityThread.java:8177) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
```

**Comment by francisco-ss-dev** [comment] 2023-12-19 14:26
SAME HERE

System:
  OS: macOS 14.2
  CPU: (8) arm64 Apple M1
  Memory: 83.19 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.2.0
    path: ~/.nvm/versions/node/v18.2.0/bin/node
  Yarn: Not Found
  npm:
    version: 8.9.0
    path: ~/.nvm/versions/node/v18.2.0/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK: Not Found
  Android SDK:
    API Levels:
      - "28"
      - "30"
      - "33"
      - "34"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 33.0.1
      - 34.0.0
    System Images:
      - android-30 | ARM 64 v8a
      - android-30 | Google APIs ARM 64 v8a
      - android-30 | Google Play ARM 64 v8a
      - android-34 | ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.11005911
  Xcode:
    version: /undefined
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.1
    wanted: 0.73.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

**Comment by DZamataev** [comment] 2023-12-20 13:30
Try setting your targetSdk to 33
![image](https://github.com/Rapsssito/react-native-background-actions/assets/2046717/5036cccf-e95f-4d17-9349-329af81dbc61)

**Comment by ng-ha** [comment] 2024-01-15 09:51
> Faced the same issue. Try setting your targetSdkVersion to 33. ![image](https://private-user-images.githubusercontent.com/2046717/291905904-5036cccf-e95f-4d17-9349-329af81dbc61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTI1NDcsIm5iZiI6MTcwNTMxMjI0NywicGF0aCI6Ii8yMDQ2NzE3LzI5MTkwNTkwNC01MDM2Y2NjZi1lOTVmLTRkMTctOTM0OS0zMjlhZjgxZGJjNjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTVUMDk1MDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDU2NjdlMTUzODI0MjE3NDMxNjRhMjg3YmYzZWYyYWNkY2ZjZTkzZGYxM2JkODgxMzI0NTI0OWU1MzJmYjk3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.azX3pVt4uuzNDIACtRIH07AExTO1l7aRmDbBP4gxtQY)

downgrade isn't good answer

**Comment by devtyty** [comment] 2024-01-17 08:21
@ng-ha you can use this patch for android 14

##Step 1: Patch this script

```diff --git a/node_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java b/node_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java
index 315dbd4..ccba9a6 100644
--- a/node_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java
+++ b/node_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java
@@ -40,8 +40,11 @@ final public class RNBackgroundActionsTask extends HeadlessJsTaskService {
             //as RN works on single activity architecture - we don't need to find current activity on behalf of react context
             notificationIntent = new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER);
         }
+
         final PendingIntent contentIntent;
-        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
+        if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
+            contentIntent = PendingIntent.getActivity(context,0, notificationIntent, PendingIntent.FLAG_MUTABLE | PendingIntent.FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT);
+        } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
             contentIntent = PendingIntent.getActivity(context, 0, notificationIntent, PendingIntent.FLAG_MUTABLE);
         } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
             contentIntent = PendingIntent.getActivity(context, 0, notificationIntent, PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE);
```

##Step 2: Update service type in your mainifest (AndroidMainifest.xml)

```<service android:name="com.asterinet.react.bgactions.RNBackgroundActionsTask" android:foregroundServiceType="shortService | ...." />```

**Comment by ng-ha** [comment] 2024-01-17 17:01
> @ng-ha you can use this patch for android 14
> 
> ```diff
> index b67ef4d..cf8cab4 100644
> --- a/node_modules/react-native-background-actions/android/src/main/AndroidManifest.xml
> +++ b/node_modules/react-native-background-actions/android/src/main/AndroidManifest.xml
> @@ -1,6 +1,6 @@
>  <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.asterinet.react.bgactions">
>      <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
>      <application>
> -        <service android:name=".RNBackgroundActionsTask"/>
> +        <service android:name=".RNBackgroundActionsTask" android:foregroundServiceType="shortService"/>
>      </application>
>  </manifest>
> diff --git a/node_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java b/node_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java
> index 315dbd4..ccba9a6 100644
> --- a/node_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java
> +++ b/node_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java
> @@ -40,8 +40,11 @@ final public class RNBackgroundActionsTask extends HeadlessJsTaskService {
>              //as RN works on single activity architecture - we don't need to find current activity on behalf of react context
>              notificationIntent = new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER);
>          }
> +
>          final PendingIntent contentIntent;
> -        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
> +        if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
> +            contentIntent = PendingIntent.getActivity(context,0, notificationIntent, PendingIntent.FLAG_MUTABLE | PendingIntent.FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT);
> +        } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
>              contentIntent = PendingIntent.getActivity(context, 0, notificationIntent, PendingIntent.FLAG_MUTABLE);
>          } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
>              contentIntent = PendingIntent.getActivity(context, 0, notificationIntent, PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE);
> ```

this worked for me. Thank you!

**Comment by nop33** [comment] 2024-03-11 12:42
I guess the problem is the "shortService"

**Comment by devtyty** [comment] 2024-03-11 15:02
> I guess the problem is the "shortService"

You can try with this pr #208

**Comment by AftabUfaq** [comment] 2024-03-15 05:49
> > I guess the problem is the "shortService"
> 
> You can try with this pr #208

I have added that but still have an issue with this. 

java.lang.RuntimeException: Unable to start service com.asterinet.react.bgactions.RNBackgroundActionsTask@e9a8a1a with Intent { cmp=com.appauthmobile/com.asterinet.react.bgactions.RNBackgroundActionsTask (has extras) }: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{3b2b00c 12531:com.appauthmobile/u0a513} targetSDK=34

**Comment by AftabUfaq** [comment] 2024-03-15 05:53
> I also ugpraded to API Level 34 and applied the patch from above. But now, after about 160 seconds of having the app in the bg, I get this message. Did any of you face that?
> 
> <img alt="image" width="391" src="https://private-user-images.githubusercontent.com/1579899/311698331-d334a3a8-be6d-49c2-b963-c80461d69425.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0ODIyMzEsIm5iZiI6MTcxMDQ4MTkzMSwicGF0aCI6Ii8xNTc5ODk5LzMxMTY5ODMzMS1kMzM0YTNhOC1iZTZkLTQ5YzItYjk2My1jODA0NjFkNjk0MjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMDU1MjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTNhNTFkZjUyODdlNDQ5ZTc1NjIwNDg2ZGJlYmU3NjNiZDNhNjZiNzg5ZDE3NDc1ZWM2YmQxMGRiYzAzMjkxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hhIqBI65v3QamK3EZVA76NsXMOvxHHQxea0wBYfP1uw">

did you solved it

**Comment by nop33** [comment] 2024-03-15 06:32
Yes. I replaced `shortService` with `dataSync`. I also had to this to my expo config:

```js
expo: {
    android: {
      permissions: [
        'android.permission.FOREGROUND_SERVICE_DATA_SYNC',
      ]
    }
}
```
 This was my patch

```diff
diff --git a/android/src/main/AndroidManifest.xml b/android/src/main/AndroidManifest.xml
index b67ef4d1837363489a1749acb852997a6c93c1b5..6aa30a826c2f17a35ccd30b64291d3d20006e864 100644
--- a/android/src/main/AndroidManifest.xml
+++ b/android/src/main/AndroidManifest.xml
@@ -1,6 +1,6 @@
 <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.asterinet.react.bgactions">
     <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
     <application>
-        <service android:name=".RNBackgroundActionsTask"/>
+        <service android:name=".RNBackgroundActionsTask" android:foregroundServiceType="dataSync" />
     </application>
 </manifest>
diff --git a/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java b/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java
index 315dbd4c10155c54302fa04e3bef5067d78003cb..9900fc0654f1cfd75acd77b46734ea144c3dcb40 100644
--- a/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java
+++ b/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java
@@ -41,7 +41,9 @@ final public class RNBackgroundActionsTask extends HeadlessJsTaskService {
             notificationIntent = new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER);
         }
         final PendingIntent contentIntent;
-        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
+        if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
+            contentIntent = PendingIntent.getActivity(context,0, notificationIntent, PendingIntent.FLAG_MUTABLE | PendingIntent.FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT);
+        } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
             contentIntent = PendingIntent.getActivity(context, 0, notificationIntent, PendingIntent.FLAG_MUTABLE);
         } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
             contentIntent = PendingIntent.getActivity(context, 0, notificationIntent, PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE);

```

**Comment by devtyty** [comment] 2024-03-15 06:38
> ```js
> FOREGROUND_SERVICE_DATA_SYNC
> ```

I thinks you should set service type in your own's app. Don't modify on the lib

**Comment by nop33** [comment] 2024-03-15 06:51
That's why I said "to my expo config". This is my own app's config file.

**Comment by AftabUfaq** [comment] 2024-03-15 06:59
> That's why I said "to my expo config". This is my own app's config file. But this is still needed to be patched:
> 
> ```
> android:foregroundServiceType="dataSync"
> ```

should I add this to android minifies file or in the patch file of AndroidManifest.xml of the project

**Comment by nop33** [comment] 2024-03-15 07:10
Sorry, I just realized that I editted `android/src/main/AndroidManifest.xml` and not `node_modules/react-native-background-actions/android/src/main/AndroidManifest.xml`, you are right.

**Comment by pratikSeven** [comment] 2024-04-04 09:12
Currently I have downgraded SDK version from 34 to 33. It is working fine but I dont think this the best idea to do.
Is there any fix for this issue ?

**Comment by nop33** [comment] 2024-04-04 09:27
What I described worked for me.

**Comment by mostasim** [comment] 2024-04-09 13:52
> Yes. I replaced `shortService` with `dataSync`. I also had to this to my expo config:
> 
> ```js
> expo: {
>     android: {
>       permissions: [
>         'android.permission.FOREGROUND_SERVICE_DATA_SYNC',
>       ]
>     }
> }
> ```
> 
> This was my patch (generated by `pnpm patch`)
> 
> ```diff
> diff --git a/android/src/main/AndroidManifest.xml b/android/src/main/AndroidManifest.xml
> index b67ef4d1837363489a1749acb852997a6c93c1b5..6aa30a826c2f17a35ccd30b64291d3d20006e864 100644
> --- a/android/src/main/AndroidManifest.xml
> +++ b/android/src/main/AndroidManifest.xml
> @@ -1,6 +1,6 @@
>  <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.asterinet.react.bgactions">
>      <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
>      <application>
> -        <service android:name=".RNBackgroundActionsTask"/>
> +        <service android:name=".RNBackgroundActionsTask" android:foregroundServiceType="dataSync" />
>      </application>
>  </manifest>
> diff --git a/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java b/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java
> index 315dbd4c10155c54302fa04e3bef5067d78003cb..9900fc0654f1cfd75acd77b46734ea144c3dcb40 100644
> --- a/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java
> +++ b/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java
> @@ -41,7 +41,9 @@ final public class RNBackgroundActionsTask extends HeadlessJsTaskService {
>              notificationIntent = new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER);
>          }
>          final PendingIntent contentIntent;
> -        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
> +        if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
> +            contentIntent = PendingIntent.getActivity(context,0, notificationIntent, PendingIntent.FLAG_MUTABLE | PendingIntent.FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT);
> +        } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
>              contentIntent = PendingIntent.getActivity(context, 0, notificationIntent, PendingIntent.FLAG_MUTABLE);
>          } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
>              contentIntent = PendingIntent.getActivity(context, 0, notificationIntent, PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE);
> ```

this works for me

**Comment by nop33** [comment] 2024-04-22 01:29
Read the docs for `shortService`, that's why you get 3 minutes. See my reply where I use `dataSync`.

**Closed** 2024-06-17 08:43 UTC

**Comment by Yashi1919** [comment] 2024-09-24 00:38
My app is still crashing on android 14 when i start my background service 


this is my manifest file 


<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.wallodynamo">

    
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.SET_WALLPAPER" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    
    
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" tools:targetApi="m" />

    
    
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"
        tools:targetApi="r" />
    
    
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:remove="android:maxSdkVersion" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:remove="android:maxSdkVersion" />
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" tools:targetApi="30"/>

    <application
        android:name=".MainApplication"
        android:label="@string/app_name"
        android:icon="@mipmap/wallo"
        android:roundIcon="@mipmap/wallo"
        android:allowBackup="false"
        android:theme="@style/AppTheme"
        android:supportsRtl="true">

        
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
            android:launchMode="singleTask"
            android:windowSoftInputMode="adjustResize"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <intent-filter android:label="filter_react_native">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="wallodynamo" />
            </intent-filter>
        </activity>

        
        <service
            android:name="com.asterinet.react.bgactions.RNBackgroundActionsTask"
            android:exported="false"
            android:foregroundServiceType="location|mediaPlayback|dataSync"
            android:permission="android.permission.BIND_JOB_SERVICE"
            tools:replace="android:foregroundServiceType">
        </service>

<service android:name="com.asterinet.react.bgactions.RNBackgroundActionsTask" 
    android:foregroundServiceType="location"/>
    </application>
</manifest>

**Comment by priyanshubuddy** [comment] 2024-09-25 08:34
> ```js
> android.permission.FOREGROUND_SERVICE_DATA_SYNC
> ```

found any solution ?

**Comment by priyanshubuddy** [comment] 2024-09-25 08:34
> My app is still crashing on android 14 when i start my background service
> 
> this is my manifest file
> 
> ```
> 
> <uses-permission android:name="android.permission.INTERNET" />
> <uses-permission android:name="android.permission.VIBRATE" />
> <uses-permission android:name="android.permission.SET_WALLPAPER" />
> <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
> <uses-permission android:name="android.permission.WAKE_LOCK" />
> <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
> 
> 
> <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
> <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" tools:targetApi="m" />
> 
> 
> 
> <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
> 
> <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"
>     tools:targetApi="r" />
> 
> 
> <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:remove="android:maxSdkVersion" />
> <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:remove="android:maxSdkVersion" />
> <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" tools:targetApi="30"/>
> 
> <application
>     android:name=".MainApplication"
>     android:label="@string/app_name"
>     android:icon="@mipmap/wallo"
>     android:roundIcon="@mipmap/wallo"
>     android:allowBackup="false"
>     android:theme="@style/AppTheme"
>     android:supportsRtl="true">
> 
>     
>     <activity
>         android:name=".MainActivity"
>         android:label="@string/app_name"
>         android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
>         android:launchMode="singleTask"
>         android:windowSoftInputMode="adjustResize"
>         android:exported="true">
>         <intent-filter>
>             <action android:name="android.intent.action.MAIN" />
>             <category android:name="android.intent.category.LAUNCHER" />
>         </intent-filter>
> 
>         <intent-filter android:label="filter_react_native">
>             <action android:name="android.intent.action.VIEW" />
>             <category android:name="android.intent.category.DEFAULT" />
>             <category android:name="android.intent.category.BROWSABLE" />
>             <data android:scheme="wallodynamo" />
>         </intent-filter>
>     </activity>
> 
>     
>     <service
>         android:name="com.asterinet.react.bgactions.RNBackgroundActionsTask"
>         android:exported="false"
>         android:foregroundServiceType="location|mediaPlayback|dataSync"
>         android:permission="android.permission.BIND_JOB_SERVICE"
>         tools:replace="android:foregroundServiceType">
>     </service>
> ```

found any solution ?

**Comment by vishalyad16** [comment] 2024-10-23 05:39
Not able to release app playstore blocking the release requesting for a video with foreground service, please help with solution! BTW why do we need FOREGROUND_SERVICE_DATA_SYNC?? 
@nop33 @DZamataev @caleblawrence @mostasim @AftabUfaq ?

**Comment by mostasim** [comment] 2024-10-23 08:58
> Not able to release app playstore blocking the release requesting for a video with foreground service, please help with solution! BTW why do we need FOREGROUND_SERVICE_DATA_SYNC?? @nop33 @DZamataev @caleblawrence @mostasim @AftabUfaq ?

@vishalyad16 Yes we need to add the permission `FOREGROUND_SERVICE_DATA_SYNC`

**Comment by Devendra7409** [comment] 2024-11-22 06:26
> @ng-ha you can use this patch for android 14
> 
> ```diff
> index b67ef4d..cf8cab4 100644
> --- a/node_modules/react-native-background-actions/android/src/main/AndroidManifest.xml
> +++ b/node_modules/react-native-background-actions/android/src/main/AndroidManifest.xml
> @@ -1,6 +1,6 @@
>  <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.asterinet.react.bgactions">
>      <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
>      <application>
> -        <service android:name=".RNBackgroundActionsTask"/>
> +        <service android:name=".RNBackgroundActionsTask" android:foregroundServiceType="shortService"/>
>      </application>
>  </manifest>
> diff --git a/node_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java b/node_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java
> index 315dbd4..ccba9a6 100644
> --- a/node_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java
> +++ b/node_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java
> @@ -40,8 +40,11 @@ final public class RNBackgroundActionsTask extends HeadlessJsTaskService {
>              //as RN works on single activity architecture - we don't need to find current activity on behalf of react context
>              notificationIntent = new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER);
>          }
> +
>          final PendingIntent contentIntent;
> -        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
> +        if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
> +            contentIntent = PendingIntent.getActivity(context,0, notificationIntent, PendingIntent.FLAG_MUTABLE | PendingIntent.FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT);
> +        } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
>              contentIntent = PendingIntent.getActivity(context, 0, notificationIntent, PendingIntent.FLAG_MUTABLE);
>          } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
>              contentIntent = PendingIntent.getActivity(context, 0, notificationIntent, PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE);
> ```

in which file in react native ?
