### ISSUE TITLE
 Cannot read property 'start' of undefined 

### ISSUE THREAD

**Issue by sitannsu** [Rapsssito/react-native-background-actions#203] opened 2023-12-18 08:29 UTC
await BackgroundService.start(veryIntensiveTask, options);  it throws  Cannot read property 'start' of undefined

**Comment by Omare123** [comment] 2024-01-10 21:17
I've been fighting this all day too.

**Comment by mr2726** [comment] 2024-02-20 10:27
Did you find a solution?

**Comment by MarkNaArea** [comment] 2024-03-07 14:02
NativeModules imported from react is an emtpy object here (I've tried to find what could be wrong in the java files, with no success yet), which lead to RNBackgroundActiong not being imported.

**Comment by MarkNaArea** [comment] 2024-03-07 16:12
PR [#208](https://github.com/Rapsssito/react-native-background-actions/pull/208) worked for me

**Comment by Rapsssito** [comment] 2024-07-09 09:57
Duplicate of #208

**Closed by Rapsssito** 2024-07-09 09:57 UTC
