### ISSUE TITLE
[ERROR] Cannot read property 'start' of null. 

### ISSUE THREAD

**Issue by aymanMFD** [Rapsssito/react-native-background-actions#222] opened 2024-05-22 09:56 UTC
When I try to start a service by pressing a button, the warning `Cannot read property 'start' of null. ` pops up.

This is my code
```js
const veryIntensiveTask = async (taskDataArguments) => {
    // Example of an infinite loop task
    console.log("Starting")
    const { delay } = taskDataArguments;
    await new Promise( async (resolve) => {
        for (let i = 0; BackgroundService.isRunning(); i++) {
            console.log(i);
            await sleep(delay);
        }
    });
};

const options = {
    taskName: 'Example',
    taskTitle: 'ExampleTask title',
    taskDesc: 'ExampleTask description',
    taskIcon: {
        name: 'appstore',
        type: 'drawable',
    },
    color: '#ff00ff',
    linkingURI: 'yourSchemeHere://chat/jane', // See Deep Linking for more info
    parameters: {
        delay: 1000,
    },
};
```
```js
const startBackgroundService = async () => {
        await BackgroundService.start(veryIntensiveTask, options);
        await BackgroundService.updateNotification({taskDesc: "This is the counter"})
    };
// More code
<TouchableOpacity onPress={startBackgroundService}>
    <Text>Start BackgroundService</Text>
</TouchableOpacity>
```

**Comment by zju1** [comment] 2024-05-27 04:03
The same here

**Comment by Rapsssito** [comment] 2024-07-09 09:57
Duplicate of #199

**Closed as completed by Rapsssito** 2024-07-09 09:57 UTC
Labels: duplicate
